### PR TITLE
margin-fix-main

### PR DESCRIPTION
**Pull request by esolar07**

### CODE REVIEW

**Comment by ondrae** [comment]
Hi @esolar07 looks like this pull request got a little messed up. Here's [the documentation](https://help.github.com/articles/creating-a-pull-request/) on how to create a pull request.

The simple version is that you fork this project, create a new branch off of master, make your changes, commit them, then make a pull request from that forked branch back into master.

**Comment by esolar07** [comment]
@ondrae Sorry, some went wrong. I followed those steps, but it stated the I did not have access to the repo. I will try again. Thanks!!!

**Comment by ondrae** [comment]
Be sure to fork it into your own account first.

**Comment by esolar07** [comment]
@ondrae Will do.

**Pull request closed without merging**
